#pragma once
// File creation: 21/05/2021 - 10:40:04
// This file was generated by cmake.
// Delete this file and recompile cmake for an update.

// the gltf scene to be loaded
//#define MODEL_NAME "models/cornellBox.gltf"
#define MODEL_NAME "models/Sponza/glTF/Sponza.gltf"
