#pragma once
// File creation: 27/05/2021 - 00:00:42
// This file was generated by cmake.


// the gltf scene to be loaded
//#define MODEL_NAME "models/cornellBox.gltf"
#define MODEL_NAME "models/Sponza/glTF/Sponza.gltf"

// whether to use shaderc to compile spirv shaders
#define RT_USE_SHADERC_SPIRV_GENERATION true
